name: codeprintio
version: '1.0.5'
summary: A powerful cross-platform tool for creating AI-ready project snapshots
description: |
  CodePrint is a high-performance, cross-platform CLI tool that creates
  comprehensive snapshots of your codebase for use with AI assistants like
  ChatGPT, Claude, and Gemini. It automatically detects project types,
  respects .gitignore rules, and generates output in multiple formats.

grade: stable
confinement: strict
base: core20

apps:
  codeprint:
    command: bin/codeprint
    plugs:
      - home
      - removable-media
      - network

parts:
  codeprint:
    plugin: python
    source: .
    python-packages:
      - colorama
      - pyperclip
    stage-packages:
      - python3-minimal